# Release drafter configuration https://github.com/release-drafter/release-drafter#configuration
# Emojis were chosen to match the https://gitmoji.carloscuesta.me/

name-template: "$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
sort-direction: ascending

categories:
  - title: ":rocket: Features"
    labels: [enhancement, feature]
  - title: ":boom: Breaking Changes"
    labels: [breaking]
  - title: ":wrench: Fixes & Refactoring"
    labels: [bug, refactoring, bugfix, fix]
  - title: ":package: Build System & CI/CD"
    labels: [build, ci, testing]
  - title: ":pencil: Documentation"
    labels: [documentation]
  - title: ":arrow_up: Dependencies updates"
    labels: [dependencies]

template: |
  ## What's Changed

  $CHANGES

  ## :busts_in_silhouette: List of contributors

  $CONTRIBUTORS

  ---

  **Full Changelog**: https://github.com/RafaelWO/unparallel/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
