# This file contains values from Cookiecutter

default_context:
  project_name: "unparallel"
  project_description: "Create async web requests in no time with `unparallel`"
  organization: "RafaelWO"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "RafaelWO"
  email: "weingartner.rafael@hotmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
