site_name: Unparallel
site_url: https://rafaelwo.github.io/unparallel/
repo_url: https://github.com/RafaelWO/unparallel
repo_name: RafaelWO/unparallel
nav:
  - Home: index.md
  - Usage: usage.md
  - Examples: examples.md
  - Releases: releases.md
  - Contributing: contributing.md
  - API Reference: reference.md
theme:
  name: material
  icon:
    logo: material/shuffle-variant
    repo: fontawesome/brands/github
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: octicons/moon-16
        name: "Switch to dark mode"

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: octicons/sun-16
        name: "Switch to light mode"
extra:
  version:
    provider: mike
    alias: true
    default: latest
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: spacy
            show_root_heading: true
            members_order: source
            show_root_members_full_path: true
            separate_signature: true
  - mike:
      canonical_version: latest
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
