site_name: Unparallel
nav:
  - Home: index.md
  - Releases: releases.md
  - Contributing: contributing.md
  - API Reference: reference.md
theme:
  name: material
  icon:
    logo: material/shuffle-variant
  features:
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          members_order: source
markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
